<a href="https://colab.research.google.com/github/pawarsakshi966-dot/Machine_Learning/blob/main/01_fetching_data_from_an_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

In [ ]:
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=bb6f2f8446e6e00a5fe0e113cb3f60c0&language=en-US&page=1')
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
   'genre_ids': [16, 28, 12, 14],
   'id': 980431,
   'title': 'Avatar Aang: The Last Airbender',
   'original_language': 'en',
   'original_title': 'Avatar Aang: The Last Airbender',
   'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
   'popularity': 81.4295,
   'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
   'release_date': '2026-07-24',
   'softcore': False,
   'video': False,
   'vote_average': 9.194,
   'vote_count': 1012},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 50.8139,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.875,
   'vote_count': 2145},
  {'adult': False,
   'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
   'genre_ids': [35, 10749],
   'id': 1632181,
   'title': 'Accidental Partners',
   'original_language': 'es',
   'original_title': 'Socias por accidente',
   'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
   'popularity': 20.4261,
   'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
   'release_date': '2026-03-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.874,
   'vote_count': 366},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 78.8073,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 8.779,
   'vote_count': 2014},
  {'adult': False,
   'backdrop_path': '/pNjh59JSxChQktamG3LMp9ZoQzp.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 79.9697,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.728,
   'vote_count': 31171},
  {'adult': False,
   'backdrop_path': '/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg',
   'genre_ids': [80, 28, 53],
   'id': 1621552,
   'title': 'Facing El Chapo',
   'original_language': 'es',
   'original_title': 'La captura',
   'overview': 'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss.',
   'popularity': 327.1505,
   'poster_path': '/alpf5v4UqSFawPmG9RX03Or4BDk.jpg',
   'release_date': '2026-08-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.787,
   'vote_count': 343},
  {'adult': False,
   'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 55.4153,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.686,
   'vote_count': 23447},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 72.0016,
   'poster_path': '/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.663,
   'vote_count': 4206},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 111.046,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.648,
   'vote_count': 7426},
  {'adult': False,
   'backdrop_path': '/pGzqRKrYeK4LogoysNro0vG8d8N.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 31.7534,
   'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 14252},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 30.0971,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 17817},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 28.9514,
   'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 10293},
  {'adult': False,
   'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
   'genre_ids': [18, 10749],
   'id': 1232449,
   'title': 'Young Hearts',
   'original_language': 'nl',
   'original_title': 'Young Hearts',
   'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
   'popularity': 16.0059,
   'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
   'release_date': '2024-10-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 306},
  {'adult': False,
   'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
   'genre_ids': [16, 28, 10749, 14],
   'id': 1218925,
   'title': 'Chainsaw Man - The Movie: Reze Arc',
   'original_language': 'ja',
   'original_title': '劇場版 チェンソーマン レゼ篇',
   'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
   'popularity': 30.6386,
   'poster_path': '/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
   'release_date': '2025-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 8.538,
   'vote_count': 1144},
  {'adult': False,
   'backdrop_path': '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 55.7844,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 36537},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 32.7193,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 18789},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 29.7433,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 19700},
  {'adult': False,
   'backdrop_path': '/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 42.1936,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 27210},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 12.5017,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.504,
   'vote_count': 4616},
  {'adult': False,
   'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 35.1199,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 21199}],
 'total_pages': 559,
 'total_results': 11167}

In [ ]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
  'genre_ids': [16, 28, 12, 14],
  'id': 980431,
  'title': 'Avatar Aang: The Last Airbender',
  'original_language': 'en',
  'original_title': 'Avatar Aang: The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 81.4295,
  'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
  'release_date': '2026-07-24',
  'softcore': False,
  'video': False,
  'vote_average': 9.194,
  'vote_count': 1012},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 50.8139,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.875,
  'vote_count': 2145},
 {'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 20.4261,
  'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.874,
  'vote_count': 366},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 78.8073,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.779,
  'vote_count': 2014},
 {'adult': False,
  'backdrop_path': '/pNjh59JSxChQktamG3LMp9ZoQzp.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 79.9697,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.728,
  'vote_count': 31171},
 {'adult': False,
  'backdrop_path': '/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg',
  'genre_ids': [80, 28, 53],
  'id': 1621552,
  'title': 'Facing El Chapo',
  'original_language': 'es',
  'original_title': 'La captura',
  'overview': 'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss.',
  'popularity': 327.1505,
  'poster_path': '/alpf5v4UqSFawPmG9RX03Or4BDk.jpg',
  'release_date': '2026-08-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.787,
  'vote_count': 343},
 {'adult': False,
  'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 55.4153,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.686,
  'vote_count': 23447},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 72.0016,
  'poster_path': '/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.663,
  'vote_count': 4206},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 111.046,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.648,
  'vote_count': 7426},
 {'adult': False,
  'backdrop_path': '/pGzqRKrYeK4LogoysNro0vG8d8N.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 31.7534,
  'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 14252},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 30.0971,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 17817},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 28.9514,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 10293},
 {'adult': False,
  'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
  'genre_ids': [18, 10749],
  'id': 1232449,
  'title': 'Young Hearts',
  'original_language': 'nl',
  'original_title': 'Young Hearts',
  'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
  'popularity': 16.0059,
  'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
  'release_date': '2024-10-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 306},
 {'adult': False,
  'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
  'genre_ids': [16, 28, 10749, 14],
  'id': 1218925,
  'title': 'Chainsaw Man - The Movie: Reze Arc',
  'original_language': 'ja',
  'original_title': '劇場版 チェンソーマン レゼ篇',
  'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
  'popularity': 30.6386,
  'poster_path': '/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
  'release_date': '2025-09-19',
  'softcore': False,
  'video': False,
  'vote_average': 8.538,
  'vote_count': 1144},
 {'adult': False,
  'backdrop_path': '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 55.7844,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 36537},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 32.7193,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 18789},
 {'adult': False,
  'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 29.7433,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 19700},
 {'adult': False,
  'backdrop_path': '/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 42.1936,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 27210},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 12.5017,
  'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.504,
  'vote_count': 4616},
 {'adult': False,
  'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 35.1199,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 21199}]

In [ ]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",81.4295,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.194,1012
1,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",50.8139,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.875,2145
2,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,20.4261,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.874,366
3,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,78.8073,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.779,2014
4,False,/pNjh59JSxChQktamG3LMp9ZoQzp.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,79.9697,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.728,31171
5,False,/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg,"[80, 28, 53]",1621552,Facing El Chapo,es,La captura,Two Mexican officers must survive the final ho...,327.1505,/alpf5v4UqSFawPmG9RX03Or4BDk.jpg,2026-08-21,False,False,8.787,343
6,False,/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",55.4153,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.686,23447
7,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",72.0016,/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg,2026-04-22,False,False,8.663,4206
8,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,111.0460,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.648,7426
9,False,/pGzqRKrYeK4LogoysNro0vG8d8N.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,31.7534,/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg,1974-12-20,False,False,8.600,14252
10,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,30.0971,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.570,17817
11,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,28.9514,/ppd84D2i9W8jXmsyInGyihiSyqz.jpg,1957-04-10,False,False,8.570,10293
12,False,/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg,"[18, 10749]",1232449,Young Hearts,nl,Young Hearts,14-year-old Elias increasingly feels like an o...,16.0059,/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg,2024-10-26,False,False,8.600,306
13,False,/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg,"[16, 28, 10749, 14]",1218925,Chainsaw Man - The Movie: Reze Arc,ja,劇場版 チェンソーマン レゼ篇,"In a brutal war between devils, hunters, and s...",30.6386,/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg,2025-09-19,False,False,8.538,1144
14,False,/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg,"[28, 80, 53]",155,The Dark Knight,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,55.7844,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,False,False,8.534,36537
15,False,/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg,"[16, 10751, 14]",129,Spirited Away,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",32.7193,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,False,False,8.534,18789
16,False,/amZavErrjrdgDwhsIdpWxHNenIx.jpg,"[14, 18, 80]",497,The Green Mile,en,The Green Mile,A supernatural tale set on death row in a Sout...,29.7433,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,False,False,8.506,19700
17,False,/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg,"[12, 14, 28]",122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,42.1936,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,False,False,8.506,27210
18,False,/84beTJf26mfhoasUlKSOiNSutyS.jpg,"[35, 18, 10749]",19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",12.5017,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,False,False,8.504,4616
19,False,/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg,"[35, 53, 18]",496243,Parasite,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",35.1199,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,False,False,8.500,21199

In [ ]:
pd.DataFrame(response.json()['results']).head(2)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",81.4295,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.194,1012
1,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",50.8139,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.875,2145

In [ ]:
temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,81.4295,9.194,1012
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,50.8139,8.875,2145
2,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,20.4261,8.874,366
3,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,78.8073,8.779,2014
4,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,79.9697,8.728,31171
5,1621552,Facing El Chapo,Two Mexican officers must survive the final ho...,2026-08-21,327.1505,8.787,343
6,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,55.4153,8.686,23447
7,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,72.0016,8.663,4206
8,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,111.0460,8.648,7426
9,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,31.7534,8.600,14252
10,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,30.0971,8.570,17817
11,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,28.9514,8.570,10293
12,1232449,Young Hearts,14-year-old Elias increasingly feels like an o...,2024-10-26,16.0059,8.600,306
13,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,30.6386,8.538,1144
14,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,55.7844,8.534,36537
15,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.7193,8.534,18789
16,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,29.7433,8.506,19700
17,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,42.1936,8.506,27210
18,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,12.5017,8.504,4616
19,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,35.1199,8.500,21199

In [ ]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []